const questions = [
        { question: "Angka selanjutnya dari deret: 2, 6, 12, 20, 30, ...", options: ["36", "40", "42", "48"], answer: 2 },
        { question: "Sebuah baju didiskon 20%, kemudian didiskon lagi 10% dari harga SETELAH diskon pertama. Jika harga awal Rp 100.000, berapa harga akhirnya?", options: ["Rp 70.000", "Rp 72.000", "Rp 75.000", "Rp 80.000"], answer: 1 },
        { question: "Mana yang TIDAK termasuk dalam kelompok berikut?", options: ["Sapi", "Kambing", "Kuda", "Harimau"], answer: 3 },
        { question: "Jika hari ini adalah hari Rabu, jatuh pada hari apakah 100 hari yang akan datang?", options: ["Senin", "Selasa", "Kamis", "Jumat"], answer: 3 },
        { question: "5 mesin dapat membuat 5 perangkat dalam waktu 5 menit. Berapa waktu yang dibutuhkan 100 mesin untuk membuat 100 perangkat?", options: ["5 menit", "20 menit", "50 menit", "100 menit"], answer: 0 },
        { question: "Anton lebih tinggi dari Budi, namun lebih pendek dari Cici. Dodi lebih tinggi dari Cici. Siapakah yang paling pendek?", options: ["Anton", "Budi", "Cici", "Dodi"], answer: 1 },
        { question: "Berapakah hasil dari: 8 + 2 × 4 - 6 ÷ 2 ?", options: ["11", "13", "17", "37"], answer: 1 },
        { question: "Deret huruf: A, C, F, J, O, ... Huruf selanjutnya adalah?", options: ["S", "T", "U", "V"], answer: 2 },
        { question: "Semua mamalia bernapas dengan paru-paru. Paus adalah mamalia. Kesimpulannya?", options: ["Paus bernapas dengan insang", "Paus bernapas dengan paru-paru", "Paus bukan ikan", "Tidak dapat disimpulkan"], answer: 1 },
        { question: "Keran A mengisi penuh bak dalam 2 jam. Keran B mengisi penuh bak dalam 3 jam. Jika dibuka bersamaan, berapa lama bak akan penuh?", options: ["1 jam 12 menit", "1 jam 30 menit", "2 jam 30 menit", "5 jam"], answer: 0 },

            // --- POLA DERET & ANGKA (25 Soal) ---
    { question: "Angka selanjutnya dari deret: 1, 4, 9, 16, 25, ...", options: ["30", "32", "36", "40"], answer: 2 },
    { question: "Angka selanjutnya dari deret: 3, 5, 8, 13, 21, ...", options: ["30", "32", "34", "36"], answer: 2 },
    { question: "Deret: 100, 99, 96, 91, 84, ... Angka selanjutnya adalah?", options: ["71", "75", "77", "80"], answer: 1 },
    { question: "Angka selanjutnya: 2, 5, 11, 23, 47, ...", options: ["90", "93", "95", "97"], answer: 2 },
    { question: "Deret huruf: C, E, H, L, ... Huruf selanjutnya?", options: ["O", "P", "Q", "R"], answer: 2 },
    { question: "Deret: 1, 8, 27, 64, ...", options: ["100", "120", "125", "144"], answer: 2 },
    { question: "Deret: 2, 3, 5, 7, 11, ...", options: ["12", "13", "14", "15"], answer: 1 },
    { question: "Huruf selanjutnya: Z, X, V, T, ...", options: ["Q", "R", "S", "U"], answer: 1 },
    { question: "Deret: 10, 5, 20, 10, 40, ...", options: ["15", "20", "30", "80"], answer: 1 },
    { question: "Angka selanjutnya: 3, 6, 18, 72, ...", options: ["144", "216", "288", "360"], answer: 3 },
    { question: "Deret huruf: A, Z, B, Y, C, ...", options: ["W", "X", "D", "V"], answer: 1 },
    { question: "Deret: 50, 45, 41, 38, ...", options: ["34", "35", "36", "37"], answer: 2 },
    { question: "Deret: 7, 14, 21, 28, ...", options: ["32", "34", "35", "36"], answer: 2 },
    { question: "Deret: 2, 4, 8, 16, 32, ...", options: ["48", "56", "64", "72"], answer: 2 },
    { question: "Angka selanjutnya: 9, 18, 27, 36, ...", options: ["42", "45", "48", "54"], answer: 1 },
    { question: "Deret huruf: B, E, H, K, ...", options: ["M", "N", "O", "P"], answer: 1 },
    { question: "Deret: 1, 2, 6, 24, 120, ...", options: ["240", "360", "720", "840"], answer: 2 },
    { question: "Deret: 13, 17, 19, 23, 29, ...", options: ["31", "33", "35", "37"], answer: 0 },
    { question: "Angka selanjutnya: 81, 27, 9, 3, ...", options: ["0", "1", "1/3", "-3"], answer: 1 },
    { question: "Deret: 12, 11, 13, 12, 14, 13, ...", options: ["12", "14", "15", "16"], answer: 2 },
    { question: "Deret huruf: M, N, O, L, R, I, ...", options: ["V", "W", "X", "Y"], answer: 0 },
    { question: "Deret: 1.5, 3, 6, 12, ...", options: ["18", "20", "24", "30"], answer: 2 },
    { question: "Deret: 4, 9, 19, 39, ...", options: ["59", "69", "79", "89"], answer: 2 },
    { question: "Deret: 100, 10, 1, 0.1, ...", options: ["0.01", "0.001", "0", "-0.1"], answer: 0 },
    { question: "Deret huruf: A, D, I, P, ...", options: ["U", "W", "Y", "Z"], answer: 2 },

    // --- MATEMATIKA ANALISIS (25 Soal) ---
    { question: "Umur Ayah 3 kali umur Budi. Jika selisih umur mereka 30 tahun, berapa umur Budi?", options: ["10", "15", "20", "25"], answer: 1 },
    { question: "Harga sepatu Rp 200.000 didiskon 25%. Berapa yang harus dibayar?", options: ["Rp 125.000", "Rp 150.000", "Rp 175.000", "Rp 180.000"], answer: 1 },
    { question: "Sebuah mobil menempuh jarak 120 km dalam 2 jam. Berapa kecepatan rata-ratanya?", options: ["40 km/jam", "50 km/jam", "60 km/jam", "70 km/jam"], answer: 2 },
    { question: "Jika 3x + 5 = 20, berapakah nilai x?", options: ["3", "4", "5", "6"], answer: 2 },
    { question: "Luas persegi panjang adalah 48 cm². Jika panjangnya 8 cm, berapakah lebarnya?", options: ["4 cm", "5 cm", "6 cm", "8 cm"], answer: 2 },
    { question: "Jika 5 orang dapat menyelesaikan pekerjaan dalam 12 hari, berapa hari yang dibutuhkan jika dikerjakan oleh 10 orang?", options: ["5 hari", "6 hari", "10 hari", "24 hari"], answer: 1 },
    { question: "Berapa 15% dari 400?", options: ["45", "50", "60", "75"], answer: 2 },
    { question: "Dalam kelas terdapat 40 siswa. 60% adalah perempuan. Berapa jumlah siswa laki-laki?", options: ["16", "20", "24", "26"], answer: 0 },
    { question: "Seutas tali dipotong menjadi dua bagian dengan rasio 2:3. Jika tali terpendek adalah 10 cm, berapa panjang tali seluruhnya?", options: ["15 cm", "20 cm", "25 cm", "30 cm"], answer: 2 },
    { question: "Berapa hasil dari 0.5 × 0.8 ?", options: ["0.04", "0.4", "4", "40"], answer: 1 },
    { question: "Sebuah segitiga memiliki alas 10 cm dan tinggi 5 cm. Berapa luasnya?", options: ["15 cm²", "25 cm²", "50 cm²", "100 cm²"], answer: 1 },
    { question: "Berapakah nilai dari 5² - 4² ?", options: ["1", "3", "9", "16"], answer: 2 },
    { question: "Tiga buah buku harganya Rp 45.000. Berapa harga 7 buah buku?", options: ["Rp 90.000", "Rp 105.000", "Rp 115.000", "Rp 120.000"], answer: 1 },
    { question: "Berapakah hasil dari 1/2 + 1/4 ?", options: ["1/6", "2/6", "3/4", "1"], answer: 2 },
    { question: "Rata-rata dari 4, 6, 8, dan 10 adalah?", options: ["6", "7", "8", "9"], answer: 1 },
    { question: "Satu gros sama dengan berapa lusin?", options: ["10", "12", "15", "144"], answer: 1 },
    { question: "Uang Amir Rp 50.000. Ia membeli buku Rp 15.000 dan pulpen Rp 7.500. Sisa uang Amir?", options: ["Rp 22.500", "Rp 25.000", "Rp 27.500", "Rp 30.000"], answer: 2 },
    { question: "Jarak kota A ke B pada peta 5 cm. Skala peta 1:1.000.000. Berapa jarak sebenarnya?", options: ["5 km", "50 km", "500 km", "5000 km"], answer: 1 },
    { question: "40% dari suatu bilangan adalah 80. Berapakah bilangan tersebut?", options: ["160", "180", "200", "240"], answer: 2 },
    { question: "Jika x = 2 dan y = 3, berapakah hasil dari 2x² + y ?", options: ["7", "11", "14", "17"], answer: 1 },
    { question: "Kereta api berangkat pukul 08:15 dan tiba pukul 10:45. Berapa lama perjalanannya?", options: ["2 jam 15 menit", "2 jam 30 menit", "2 jam 45 menit", "3 jam"], answer: 1 },
    { question: "Pekerja A selesai dalam 4 hari, pekerja B dalam 4 hari. Jika bersama-sama?", options: ["1 hari", "2 hari", "4 hari", "8 hari"], answer: 1 },
    { question: "Perbandingan kelereng Andi dan Budi 3:4. Jumlah kelereng mereka 35. Kelereng Budi?", options: ["15", "20", "25", "30"], answer: 1 },
    { question: "Suhu dari 25°C jika dinaikkan 40% menjadi?", options: ["30°C", "35°C", "40°C", "45°C"], answer: 1 },
    { question: "Jika 2^x = 32, berapakah nilai x?", options: ["3", "4", "5", "6"], answer: 2 },

    // --- LOGIKA PENALARAN & SILOGISME (25 Soal) ---
    { question: "Semua bunga mawar berwarna merah. Beberapa bunga di taman adalah mawar. Kesimpulannya?", options: ["Semua bunga di taman merah", "Beberapa bunga di taman merah", "Tidak ada mawar di taman", "Semua bunga merah adalah mawar"], answer: 1 },
    { question: "Tina duduk di sebelah kanan Rio. Andi duduk di sebelah kiri Rio. Siapa di tengah?", options: ["Tina", "Andi", "Rio", "Tidak diketahui"], answer: 2 },
    { question: "Jika Hujan maka Jalan Basah. Jalan tidak basah. Kesimpulannya?", options: ["Sedang Hujan", "Tidak Hujan", "Jalan kering karena panas", "Hujan rintik-rintik"], answer: 1 },
    { question: "Budi bangun lebih pagi dari Candra. Dika bangun lebih lambat dari Budi. Siapa yang paling pagi?", options: ["Budi", "Candra", "Dika", "Candra dan Dika sama"], answer: 0 },
    { question: "Tidak ada siswa malas yang lulus. Andi lulus ujian. Kesimpulannya?", options: ["Andi siswa rajin", "Andi siswa malas", "Andi mungkin malas", "Tidak dapat disimpulkan"], answer: 0 },
    { question: "Ibu pergi ke pasar setiap 3 hari sekali. Jika hari ini Senin Ibu ke pasar, hari apa Ibu ke pasar lagi?", options: ["Rabu", "Kamis", "Jumat", "Sabtu"], answer: 1 },
    { question: "Lantai 1 lebih rendah dari lantai 2. Lantai 3 lebih tinggi dari lantai 2. Lantai mana tertinggi?", options: ["Lantai 1", "Lantai 2", "Lantai 3", "Sama tinggi"], answer: 2 },
    { question: "Sebuah jam dinding menunjukkan pukul 03.15. Berapa derajat sudut terkecil antara jarum jam dan menit?", options: ["0 derajat", "7.5 derajat", "15 derajat", "22.5 derajat"], answer: 1 },
    { question: "Burung : Terbang = Ikan : ?", options: ["Sisik", "Berenang", "Air", "Insang"], answer: 1 },
    { question: "Gelap : Terang = Menangis : ?", options: ["Sedih", "Tertawa", "Marah", "Diam"], answer: 1 },
    { question: "Semua pohon berdaun hijau. Kaktus tidak berdaun hijau. Kesimpulannya?", options: ["Kaktus adalah pohon", "Kaktus bukan pohon", "Kaktus pohon yang aneh", "Tidak dapat disimpulkan"], answer: 1 },
    { question: "Jono lebih tua dari pada Joni, tapi lebih muda dari pada Jini. Siapa yang paling muda?", options: ["Jono", "Joni", "Jini", "Sama umur"], answer: 1 },
    { question: "Bulan : Bumi = Bumi : ?", options: ["Bintang", "Matahari", "Tata Surya", "Galaksi"], answer: 1 },
    { question: "Buku : Membaca = Garpu : ?", options: ["Makan", "Dapur", "Sendok", "Piring"], answer: 0 },
    { question: "Ahmad selalu berbohong. Ia berkata 'Aku sedang berbohong'. Pernyataan ini?", options: ["Benar", "Salah", "Paradoks", "Tidak bermakna"], answer: 2 },
    { question: "Semua murid membawa pensil. Sebagian murid membawa penghapus. Kesimpulannya?", options: ["Semua bawa penghapus", "Yang bawa penghapus pasti bawa pensil", "Yang bawa pensil tidak bawa penghapus", "Tidak ada kesimpulan"], answer: 1 },
    { question: "Motor : Bensin = Manusia : ?", options: ["Kaki", "Udara", "Makanan", "Otot"], answer: 2 },
    { question: "Jika A=1, B=2, C=3, berapakah nilai kata 'BACA'?", options: ["5", "6", "7", "8"], answer: 2 },
    { question: "Lari : Lelah = Makan : ?", options: ["Lapar", "Kenyang", "Tidur", "Minum"], answer: 1 },
    { question: "Ular : Merayap = Katak : ?", options: ["Berenang", "Melompat", "Menyelam", "Terbang"], answer: 1 },
    { question: "Kaca : Rapuh = Besi : ?", options: ["Kuat", "Berat", "Karat", "Panas"], answer: 0 },
    { question: "Kakak berlari lebih cepat dari Adik. Ayah lebih lambat dari Kakak namun lebih cepat dari Adik. Siapa paling lambat?", options: ["Kakak", "Adik", "Ayah", "Ibu"], answer: 1 },
    { question: "Pisau : Memotong = Sapu : ?", options: ["Lantai", "Membersihkan", "Kotoran", "Debu"], answer: 1 },
    { question: "Utara : Selatan = Timur : ?", options: ["Tenggara", "Barat", "Timur Laut", "Utara"], answer: 1 },
    { question: "Es : Dingin = Api : ?", options: ["Asap", "Merah", "Panas", "Kayu"], answer: 2 },

    // --- PENGETAHUAN UMUM & PENGENALAN (15 Soal) ---
    { question: "Mana yang TIDAK termasuk alat indra?", options: ["Mata", "Telinga", "Jantung", "Kulit"], answer: 2 },
    { question: "Mana yang berbeda dari kelompok ini?", options: ["Apel", "Jeruk", "Pisang", "Bayam"], answer: 3 },
    { question: "Mata uang negara Jepang adalah?", options: ["Won", "Yen", "Yuan", "Baht"], answer: 1 },
    { question: "Mana yang berbeda dari kelompok ini?", options: ["Gitar", "Piano", "Drum", "Seruling"], answer: 2 },
    { question: "Sinonim dari kata 'EKSKAVASI' adalah?", options: ["Pembangunan", "Penggalian", "Penghancuran", "Penelitian"], answer: 1 },
    { question: "Antonim dari kata 'PROLOG' adalah?", options: ["Epilog", "Monolog", "Dialog", "Katalog"], answer: 0 },
    { question: "Ibukota dari provinsi Jawa Timur adalah?", options: ["Semarang", "Yogyakarta", "Bandung", "Surabaya"], answer: 3 },
    { question: "Mana yang merupakan benda cair pada suhu ruangan?", options: ["Besi", "Emas", "Raksa", "Tembaga"], answer: 2 },
    { question: "Hewan apa yang bernapas menggunakan kulit?", options: ["Kucing", "Burung", "Cacing", "Ikan"], answer: 2 },
    { question: "Mana yang TIDAK termasuk benua?", options: ["Eropa", "Asia", "Rusia", "Afrika"], answer: 2 },
    { question: "Planet terdekat dari matahari adalah?", options: ["Venus", "Bumi", "Mars", "Merkurius"], answer: 3 },
    { question: "Siapakah penemu bola lampu pijar?", options: ["Nikola Tesla", "Thomas Alva Edison", "Albert Einstein", "Isaac Newton"], answer: 1 },
    { question: "Gunung tertinggi di dunia adalah?", options: ["G. Kilimanjaro", "G. Everest", "G. Fuji", "G. Jayawijaya"], answer: 1 },
    { question: "Alat untuk mengukur tekanan udara adalah?", options: ["Termometer", "Barometer", "Anemometer", "Higrometer"], answer: 1 },
    { question: "Benua yang dijuluki sebagai Benua Biru adalah?", options: ["Asia", "Eropa", "Amerika", "Australia"], answer: 1 }

];
